### ISSUE TITLE
Support all meta-data types

### ISSUE THREAD

**Issue by ChuckJonas** [ChuckJonas/vscode-salesforce-diff#1]
Currently it just supports apex classes (and that's pretty hackish).   Should add support for all/most metadata types.

It would make this ALOT easier if we could pass a flag to the `sfdx force:source:retrieve` [command](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_source.htm#cli_reference_retrieve) that would allow you to specify an output directory (instead of it just overwriting the input)

Otherwise we'll need to rewrite a lot of the same functionality to resolve the local files with their remote counterparts.  And unfortunately the `@saleforce/alm` package which contains the commands isn't technically open-sourced...

@ntotten any thoughts on this?

**Comment by ntotten** [comment]
We do plan on adding this feature. We are working on related conflict detection now. We do have plans to implement the CLI command you suggest, but it will probably be at least a month or two before we ship it due to some internal engineering work that has the CLI team fairly busy at the moment.
