### ISSUE TITLE
Error when trying to find the diff

### ISSUE THREAD

**Issue by mailbala** [ChuckJonas/vscode-salesforce-diff#4]
When I give 'Diff with Salesforce', I get the below error. I have only one org in my setup

"Unable to open 'AccountTriggerHandlerTest Local vs. Salesforce': Cannot read property 'Body' of undefined."

Please let me know how to resolve this issue.

**Comment by mailbala** [comment]
I guess we don't need to specify file extension (.cls) in the soql query 
SELECT Name, Body FROM ApexClass WHERE Name = '${path.basename(uri.fsPath,'.cls')}
Query should look

SELECT Name, Body FROM ApexClass WHERE Name = 'myclassname'

**Comment by ChuckJonas** [comment]
`${path.basename(uri.fsPath,'.cls')}` actually does remove the `.cls` extension.  

Did you confirm that the file actually existed on the projects default sfdx org?

**Comment by ChuckJonas** [comment]
A output channel has been added which offers additional insight helpful with debugging.  If you are still experiencing this issue, please run the command and paste the result of the output channel in here (feel free to reopen the issue)
