### ISSUE TITLE
Unable to open 'MyFileName Local vs. Salesforce': Cannot read property 'Body' of undefined.

### ISSUE THREAD

**Issue by RandallFlagg** [ChuckJonas/vscode-salesforce-diff#5]
When trying to diff a file no diff is shown and the following error shows in a small window on the bottom corner with the following message:

> Unable to open 'MyFileName Local vs. Salesforce': Cannot read property 'Body' of undefined.

**Comment by ChuckJonas** [comment]
A output channel has been added which offers additional insight helpful with debugging.  If you are still experiencing this issue, please run the command and paste the result of the output channel in here (feel free to reopen the issue)
