### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by cvuyyuru** [ChuckJonas/vscode-salesforce-diff#7]
Unable to open 'CancellationScheduler Local vs. Salesforce': Cannot read property 'Body' of undefined.

**Comment by ChuckJonas** [comment]
A output channel has been added which offers additional insight helpful with debugging.  If you are still experiencing this issue, please run the command and paste the result of the output channel in here (feel free to reopen the issue)

**Comment by lakhani1** [comment]
Unable to open 'className: Local vs Salesforce': ENOENT: no such file or directory, copyfile '....\sfdx-project.json' -> '........\AppData\Roaming\Code\User\workspaceStorage\b2767e239961c44eafb1c97c09db2acd\chuckjonas.salesforce-diff\........\sfdx-project.json'.

**Comment by gauravj29** [comment]
Still Facing the same issue @ChuckJonas
